title: "Test Academic Pages"
name: "My Test Site"
description: "Just testing Academic Pages theme"
author:
  name: "Test Author"
  avatar: "images/profile.jpg"  # Or remove if you don't have a photo yet
  bio: "A short bio goes here"
  email: "author@example.com"
  # etc.

remote_theme: academicpages/academicpages.github.io@v0.8.3

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
